### ISSUE TITLE
Rozměry PCB

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/QFHBAL01#3]
Tak sem si aktuální plošný spoj zkusil okótovat.

![image](https://user-images.githubusercontent.com/1194177/97322817-7566b080-1870-11eb-830a-784ee3a460f8.png)

Výsledkem je zjištění, že plošný spoj je větší, než průměr antény na 868 MHz, který je asi 57 mm. 

Plošný spoj tak úplně nerespektuje [původní plán použití](https://github.com/cernohorsky/QFH-Antenna-868MHz/issues/1), jak tak zřejmě nutné jej zmenšit.

**Comment by roman-dvorak** [comment]
Nemohl by mít tvar nějakého osmiúhelníku?

**Comment by kaklik** [comment]
> Nemohl by mít tvar nějakého osmiúhelníku?

To nevyřeší celkovou velikost.. Ale když bude jinej než pravoúhlej, tak pak už může být klidně i kulatý. Protože jde už jen o rozdíl dělení drážkováním a dělení frézováním.
