### ISSUE TITLE
Kontrola DRC

### ISSUE THREAD

**Issue by ChroustJan** [ODZ-UJF-AV-CR/QFHBAL01#5]
Mě DRC kontrola ukazuje takovouto šílenos:
![image](https://user-images.githubusercontent.com/9783606/98443540-2dffe000-210c-11eb-8c04-40d2f855a630.png)

Chtělo by provést nějakou optimalizaci, aby se nezanedbala nějaká důležitá chyba.

**Comment by kaklik** [comment]
Tak jsem zjistil, že ty potíže jsou z velký části způsobený tímhle: 

![image](https://user-images.githubusercontent.com/1194177/98584042-9b0aa580-22c5-11eb-9387-e9fe1888606c.png)

@cernohorsky  z nějakého důvodu dal do každého výstupu dvě plošky, které jsou THT a jsou nad sebou. Důsledkem pak je, že DRC si pak takhle stěžuje. Redundantní plošky jsem odstranil. 

DRC pak zdá se dobře nefunguje na kulatém PCB a vytváří mnoho zřejmě falešných hlášek tohoto typu: 

![image](https://user-images.githubusercontent.com/1194177/98585529-b7a7dd00-22c7-11eb-8d5d-93aae9533e30.png)

Další problematická hláška je unconnected vias. Která vzniká v případě, že se do plošky dají vias, které ale nemají připojený žádný net. 

V obou těchto případech jde buď o chybu kicadu a nebo o velmi specifické použití. Takže jsem tyto dvě chyby v DRC zakázal. 
Výsledkem je, že si DRC už na žádné další chyby nestěžuje.

**Comment by ChroustJan** [comment]
Odesláno do výroby.
