### ISSUE TITLE
QFHBAL01 osadit MCX konektorem

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/QFHBAL01#6]
Moduly je možné osadit bez RF konektoru, ten klidně naletuju sám.  Je ale potřeba minimálně pro 3ks mít MCX konektor jak na kabel RG-174, tak i do PCB.

**Comment by ChroustJan** [comment]
@kaklik  dle seznamu vyrobím 6ks bez konektoru.

**Comment by kaklik** [comment]
Tohle se stalo redundantním k https://github.com/ODZ-UJF-AV-CR/FIK-6/issues/13
